---

- name: Configure Raspberry Pi

  hosts: pi
  remote_user: pi
  sudo: yes
  vars_prompt:
    - name: wifi_ssid
      prompt: "Enter wifi SSID"
      default: 'N'

    - name: wifi_pass
      prompt: "Enter wifi password"
      default: 'N'

  roles:
    - { role: wifi, when: wifi_ssid != 'N' and wifi_pass != 'N' }
    - core
