---

- name: Configure Raspberry Pi

  hosts: pi
  remote_user: pi
  sudo: yes
  vars_prompt:
    - name: wifi_ssid
      prompt: "Enter wifi SSID"
      default: 'N'

    - name: wifi_pass
      prompt: "Enter wifi password"
      default: 'N'

    - name: mod_pass
      prompt: "Enter MPD password"
      default: 'N'

    - name: disable_camera_led
      prompt: "Disable camera LED?"
      default: 'N'

    - name: eyefi_id
      prompt: "Enter eye-fi card ID"
      default: 'N'

    - name: eyefi_key
      prompt: "Enter eye-fi card public key"
      default: 'N'

  roles:
    - { role: wifi, when: wifi_ssid != 'N' and wifi_pass != 'N' }
    - core
    - camera
    - { role: mpd_host, when: mpd_pass != 'N' }
    - { role: eyefi_host, when: eyefi_id != 'N' and eyefi_key != 'N' }
